const ALIAS_MAP = {
    "8man sus viejas": "Yahari Ore no Seishun Love Comedy wa Machigatteiru.",
    "akiba maid war": "Akiba Maid War",
    "amazing spiderman": "The Amazing Spider-Man",
    "anime voleyball": "Haikyu!!",
    "anime voleyboll": "Haikyu!!",
    "haikyuu": "Haikyu!!",
    "aventuras pajin": "Mushoku Tensei",
    "aventuras pajin s3cap": "Mushoku Tensei",
    "baki": "Baki",
    "black clover": "Black Clover",
    "bleach": "Bleach",
    "blich": "Bleach",
    "blich infierno": "Bleach",
    "blich tybw": "Bleach: Thousand-Year Blood War",
    "boku no hero academia": "My Hero Academia",
    "boku no pico romance": "Boku no Pico",
    "bomberos horny": "Fire Force",
    "caballeros del sobaco": "Saint Seiya",
    "calabozos tragones >w<": "Delicious in Dungeon",
    "calabozos tragones xdd": "Delicious in Dungeon",
    "capi tanga amaerica civil hard": "Captain America: Civil War",
    "casa no hay papel": "La Casa de Papel",
    "chicas magicas": "Puella Magi Madoka Magica",
    "cholos japoneses anime": "Tokyo Revengers",
    "cientificos viajes tiempo": "Steins;Gate",
    "code geass": "Code Geass",
    "codigo traje rojo": "Codigo Traje Rojo",
    "cronicas shannara": "The Shannara Chronicles",
    "deadman wonderland": "Deadman Wonderland",
    "destino babilonia": "Fate/Grand Order - Absolute Demonic Front: Babylonia",
    "destino fake": "Fate/strange Fake",
    "destino go": "Fate/Grand Order",
    "detective guapo pass": "Psycho-Pass",
    "digimon": "Digimon",
    "diosa inutil": "DanMachi",
    "diosa unutil t4": "DanMachi",
    "dioses vs humanos": "Record of Ragnarok",
    "dioses vs humanos mitad": "Record of Ragnarok",
    "dioses vs humanos t2": "Record of Ragnarok",
    "dr piedra": "Dr. Stone",
    "dr strange": "Doctor Strange",
    "ecchi tail": "Fairy Tail",
    "efren retumbe": "Attack on Titan",
    "elfa sus panas": "Frieren: Beyond Journey's End",
    "ergo proxy": "Ergo Proxy",
    "escuadron suicida": "Suicide Squad",
    "exorcista su harem": "Ao no Exorcist",
    "familia espias": "Spy x Family",
    "familia espias konoshuba": "KonoSuba",
    "farmea duendes": "Goblin Slayer",
    "farmea duendes mitad": "Goblin Slayer",
    "farmea duendes op": "One Piece",
    "fategod zero": "Fate/Zero",
    "fatezzzz grand order babylonia": "Fate/Grand Order - Absolute Demonic Front: Babylonia",
    "fire force": "Fire Force",
    "flipantes aventuras dos hermanos": "Fullmetal Alchemist",
    "ghost in shell": "Ghost in the Shell",
    "gintama": "Gintama",
    "got serie twtich": "Game of Thrones",
    "grand blue": "Grand Blue Dreaming",
    "guilty crown twittch": "Guilty Crown",
    "harry popote anime": "Mashle",
    "hellsing": "Hellsing",
    "heroe cauteloso": "Cautious Hero: The Hero Is Overpowered but Overly Cautious",
    "hombre fierro": "Iron Man",
    "hombre fierro capi unites": "The Avengers",
    "hombre tarantula": "Spider-Man",
    "hombres mamados": "JoJo's Bizarre Adventure",
    "inciamos calabozos ytragones >w<": "Delicious in Dungeon",
    "ippo": "Hajime no Ippo",
    "ipoconda": "Hajime no Ippo",
    "iruma cum": "Welcome to Demon School! Iruma-kun",
    "isekai aristocrata shota chetado": "The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat",
    "isekai asesino": "The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat",
    "isekai feo": "Tsukimichi: Moonlit Fantasy",
    "jot0z bizzarro": "JoJo's Bizarre Adventure",
    "jujutsu kaisen": "Jujutsu Kaisen",
    "kayu numero": "Kaiju No. 8",
    "ken asura": "Kengan Ashura",
    "ken asura lloro": "Kengan Ashura",
    "ken shura": "Kengan Ashura",
    "kokun": "Dragon Ball",
    "kong isla calavera": "Kong: Skull Island",
    "kong vs godzilla": "Godzilla vs. Kong",
    "konoshuba": "KonoSuba",
    "konosuba": "KonoSuba",
    "kukun super": "Dragon Ball Super",
    "kuroko basket": "Kuroko's Basketball",
    "leyenda korra": "The Legend of Korra",
    "loli nazhi": "Saga of Tanya the Evil",
    "louise zero": "The Familiar of Zero",
    "made in abbys krimetsu": "Made in Abyss",
    "maistro aigres": "Avatar: The Last Airbender",
    "maquia historia amor \u2267\u03c9\u2266 ection": "Maquia: When the Promised Flower Blooms",
    "maraton blich": "Bleach",
    "meme gol": "Blue Lock",
    "mi rey bocchi": "Ranking of Kings",
    "mi rey boji": "Ranking of Kings",
    "mob psycho": "Mob Psycho 100",
    "monstruos vs aliens": "Monsters vs. Aliens",
    "nalgas toro": "Don't Toy with Me, Miss Nagatoro",
    "naruto verde": "My Hero Academia",
    "nier automata": "NieR:Automata Ver1.1a",
    "ninos lobos": "Wolf Children",
    "no edit efren retumbe": "Attack on Titan",
    "no laif": "No Game No Life",
    "no lif": "No Game No Life",
    "ojos rojos mi amiga cosplayer": "My Dress-Up Darling",
    "one piece live action": "One Piece",
    "op": "One Piece",
    "orgasmos culinarios": "Food Wars! Shokugeki no Soma",
    "origen guardianes": "Rise of the Guardians",
    "otakuverso kiritogod": "Sword Art Online",
    "otomegod sekai": "Trapped in a Dating Sim: The World of Otome Games is Tough for Mobs",
    "overflo lord": "Overlord",
    "overflow lord": "Overlord",
    "padre ball z broly esencia": "Dragon Ball Z: Broly - The Legendary Super Saiyan",
    "padre ball z galaxia corre": "Dragon Ball Z: Bojack Unbound",
    "padre vs hijo": "Baki",
    "panaderos zodiaco": "Saint Seiya: The Lost Canvas",
    "panas miku": "The Quintessential Quintuplets",
    "pandilla espacio": "Guardians of the Galaxy",
    "pasion montana": "JoJo's Bizarre Adventure",
    "pastilla azul": "The Matrix",
    "pecados capitales": "The Seven Deadly Sins",
    "pecados capitales jinetes": "The Seven Deadly Sins",
    "pecados capitales prisioneros cielo": "The Seven Deadly Sins",
    "pelea espadas cour tybw": "Bleach: Thousand-Year Blood War",
    "piano violin": "Your Lie in April",
    "piba timida no edit": "Komi Can't Communicate",
    "pibe calvo": "One Punch Man",
    "pibe calvo anime": "One Punch Man",
    "pibe motosierra": "Chainsaw Man",
    "pibe siquico": "Mob Psycho 100",
    "pulpo amarillo": "Assassination Classroom",
    "pulpo amarillo r i p": "Assassination Classroom",
    "quiero comerme tu higado": "I Want to Eat Your Pancreas",
    "ranking party": "Ranking of Kings",
    "rayo macuin": "Cars",
    "re zero": "Re:Zero \u2212 Starting Life in Another World",
    "regalo prometido": "Jingle All the Way",
    "roxygod sus panas": "Mushoku Tensei",
    "rusa naruto": "Alya Sometimes Hides Her Feelings in Russian",
    "saitama nino": "Mob Psycho 100",
    "sakamoto days": "Sakamoto Days",
    "saramambiches hanma": "Baki Hanma",
    "secreto montana": "Secreto Montana",
    "shadow garden": "The Eminence in Shadow", // I am here
    "shangri frontier": "Shangri-La Frontier",
    "shinji subte chingado meca": "Neon Genesis Evangelion",
    "shuumatsu no valkyrie": "Record of Ragnarok",
    "shuumatsu t2 p2": "Record of Ragnarok",
    "sincensura efren retumbe": "Attack on Titan",
    "sono bisque doll": "My Dress-Up Darling",
    "summer time": "Summertime Rendering",
    "tiempo contigo": "Weathering with You",
    "tiempo dorado": "Golden Time",
    "tiene como hormiga": "Ant-Man",
    "tocandole bolas dragon \u2267\u03c9\u2266": "Dragon Ball",
    "uma musume": "Uma Musume: Pretty Derby",
    "uma musume new era": "Uma Musume: Pretty Derby",
    "uma musume ntr": "Uma Musume: Pretty Derby",
    "uma musume ouguri": "Uma Musume: Pretty Derby",
    "violet evergarden": "Violet Evergarden",
    "votacion kaguyaova": "Kaguya-sama: Love Is War",
    "voz silenciosa": "A Silent Voice",
    "abismo": "Made in Abyss",
    "alien": "Alien",
    "amagi": "Amagi Brilliant Park",
    "anime boticaria": "The Apothecary Diaries",
    "ansatsu": "Assassination Classroom",
    "aranita": "So I'm a Spider, So What?",
    "bakemonogatari": "Bakemonogatari",
    "bakigod": "Baki",
    "boticaria": "The Apothecary Diaries",
    "carlote": "Charlotte",
    "cazador": "Hunter x Hunter",
    "conjuro": "The Conjuring",
    "cote": "Classroom of the Elite",
    "doctores": "Doctores",
    "fate": "Fate/stay night",
    "fate \u2267\u03c9\u2266": "Fate/stay night",
    "fatezzz": "Fate/stay night",
    "godtama": "Gintama",
    "godttama": "Gintama",
    "godzilla": "Godzilla",
    "hulkzzz": "The Incredible Hulk",
    "hunter": "Hunter x Hunter",
    "hxh": "Hunter x Hunter",
    "ichigo": "Bleach",
    "ippogod": "Hajime no Ippo",
    "it": "It",
    "jjk": "Jujutsu Kaisen",
    "kirito": "Sword Art Online",
    "kiritogod": "Sword Art Online",
    "libretita": "Death Note",
    "megamente": "Megamind",
    "mindhunter": "Mindhunter",
    "minecraft": "Minecraft",
    "monster": "Monster",
    "naruto": "Naruto",
    "nisemonogatari": "Nisemonogatari",
    "overlord": "Overlord",
    "presagio": "Knowing",
    "rambo": "Rambo",
    "sao": "Sword Art Online",
    "saw": "Saw",
    "ttgl": "Gurren Lagann",
    "ultron": "Avengers: Age of Ultron",
    "vingalandia": "Vinland Saga",
    "k-on": "K-ON",
    "ant-man y la avispa": "Ant-Man",
    "avengers: infinity war": "Avengers: Infinity War",
    "thor: ragnarok": "Thor: Ragnarok",
    "spiderman: homecoming": "Spider-Man: Homecoming",
    "black panther": "Black Panther",
    "the amazing spiderman 2": "The Amazing Spider-Man 2",
    "shangri-la frontier": "Shangri-La Frontier",
    "uma musume new era película": "Uma Musume: Pretty Derby",
    "la leyenda de korra": "The Legend of Korra",
    "código: traje rojo": "Codigo Traje Rojo",
    "el origen de los guardianes": "Rise of the Guardians",
    "el regalo prometido": "Jingle All the Way",
    "el maistro aigres": "Avatar: The Last Airbender",
    "kong: la isla calavera": "Kong: Skull Island",
    "capibara": "Capibara",
    "entrenando waifu": "Entrenando Waifu",
    "kill": "Kill la Kill",
    "cuatro": "The Seven Deadly Sins: Four Knights of the Apocalypse",
    "morras": "The 100 Girlfriends Who Really, Really, Really, Really, Really Love You",
    "anime manuela": "Anime Manuela",
    "farmeando ando": "Farmeando Ando",
    "vemos anime jefri": "Vemos Anime Jefri",
    "edgy grandota": "Edgy Grandota",
    "jinetes": "The Seven Deadly Sins: Four Knights of the Apocalypse",
    "ojos rojos": "Kaguya-sama: Love Is War",
    "pelea espadas": "Pelea Espadas",
    "sofi anime": "Sofi Anime",
    "anime jefa": "Anime Jefa",
    "anime jefa twich": "Anime Jefa",
    "aventuras hermanos": "Fullmetal Alchemist",
    "extensible": "Extensible",
    "flipantes aventuras hermanos t2": "Fullmetal Alchemist",
    "loca pelirosa": "The Future Diary",
    "nocopy aventuras hermanos": "Fullmetal Alchemist",
    "sin nombre": "86",
    "extensible peliculas": "Safe Pelicula -  Ranking of Kings",
    "leyenda pajas¡¡": "El Pajas",
    "peliculas hermanas busca su profesor": "The Quintessential Quintuplets",
    "godzilla y kong": "Godzilla vs. Kong",
    "spiderman": "Spider-Man",
    "marvel": "Marvel",
    "ant-man": "Ant-Man",
    "amnesia montana": "Amnesia Montana",
    "betatester": "Sword Art Online: Alicization - Temporada 3",
    "noche chamuco": "Noche Chamuco",
    "flipantes aventuras hermanas": "The Quintessential Quintuplets",
    "que pica": "Spider-Man",
    "votacion": "Votacion",
    "calificando ending": "Calificando Ending",
    "cumpleanos owo": "Cumpleanos OWO",
    "ending party ranking": "Ending Party Ranking",
    "flipantes aventuras dos rubios": "Fullmetal Alchemist",
    "gato": "Gato",
    "jueves random riko sus panas": "Jueves Random Riko SUS Panas",
    "mi abuelo vs paloma cerro": "MI Abuelo VS Paloma Cerro",
    "munecon": "Munecon",
    "noche juegos terror sofi": "Noche Juegos Terror Sofi",
    "pajas": "El Pajas",
    "pajas no estas solo": "El Pajas",
    "pajas no puedes regresar": "El Pajas",
    "pijamada peliculas terror": "Pijamada Peliculas Terror",
    "primer irl": "Primer IRL",
    "reparacion congelador": "Reparacion Congelador",
    "sabado box": "Sabado BOX",
    "planeta mexicano": "Planeta Mexicano",
    "dj poniendo rolas chidas": "DJ Poniendo Rolas Chidas",
    "crossover tortilla": "Crossover Tortilla",
    "especial howelin": "Especial Howelin",
    "extensible casa cartoon": "Extensible Casa Cartoon",
    "extensible navideno": "Extensible Navideno",
    "mamadas seyr esto se queda": "Mamadas Seyr Esto SE Queda",
    "raps db": "Dragon Ball",
    "terminamos melolas extensiblllllllle >w<": "Extensible",
    "viejos lesbianos vs trasvestis espaciales": "Viejos Lesbianos VS Trasvestis Espaciales",
};
