window.CONTENT_STATE = {
  "generated_at": "2026-03-28T23:06:33.737Z",
  "rankings": {
    "recent_added": [
      "K-ON",
      "Digimon",
      "Marvel",
      "Uma Musume: Pretty Derby",
      "Spider-Man",
      "My Dress-Up Darling",
      "Mindhunter",
      "Shangri-La Frontier",
      "Sakamoto Days",
      "Uma Musume: Pretty Derby: Movies & Specials",
      "My Hero Academia",
      "The Legend of Korra",
      "Monsters vs. Aliens",
      "One Piece",
      "Codigo Traje Rojo",
      "Rise of the Guardians",
      "Hellsing",
      "Jingle All the Way",
      "Record of Ragnarok",
      "MonsterVerse",
      "Grand Blue Dreaming",
      "Knowing",
      "NieR:Automata Ver1.1a",
      "Nisemonogatari",
      "Akiba Maid War",
      "Avatar: The Last Airbender",
      "Summertime Rendering",
      "Kong: Skull Island",
      "Bakemonogatari",
      "Kill la Kill",
      "Megamind",
      "Capibara",
      "The Apothecary Diaries",
      "Blue Lock",
      "Primer IRL",
      "The 100 Girlfriends Who Really, Really, Really, Really, Really Love You",
      "Tsukimichi: Moonlit Fantasy",
      "Brokeback Mountain",
      "KonoSuba: Movies & Specials",
      "Viejos Lesbianos VS Trasvestis Espaciales",
      "KonoSuba",
      "Amnesia Montana",
      "The Seven Deadly Sins: Four Knights of the Apocalypse",
      "El Pajas",
      "Golden Time",
      "Farmeando Ando",
      "Delicious in Dungeon",
      "Mamadas Seyr Esto SE Queda",
      "El Pajas: Movies & Specials",
      "Neon Genesis Evangelion",
      "The Seven Deadly Sins: Movies & Specials",
      "Alien",
      "Extensible",
      "Rambo",
      "The Seven Deadly Sins",
      "Anime Jefa",
      "Haikyu!!: Movies & Specials",
      "Haikyu!!",
      "Bleach: Thousand-Year Blood War",
      "Extensible Navideno",
      "JoJo's Bizarre Adventure",
      "The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat",
      "Naruto",
      "DanMachi",
      "Sabado BOX",
      "Especial Howelin: Movies & Specials",
      "Vemos Anime Jefri",
      "Jujutsu Kaisen",
      "Cumpleanos OWO",
      "Bleach: Movies & Specials",
      "La Casa de Papel",
      "Kengan Ashura",
      "Dragon Ball Z: Movies & Specials",
      "Alya Sometimes Hides Her Feelings in Russian",
      "Mashle",
      "Planeta Mexicano",
      "Steins;Gate",
      "Death Note",
      "Sword Art Online: Movies & Specials",
      "Kaiju No. 8",
      "Mushoku Tensei",
      "Edgy Grandota",
      "Puella Magi Madoka Magica: Movies & Specials",
      "Ranking of Kings",
      "Extensible Peliculas: Movies & Specials",
      "Extensible Casa Cartoon",
      "QUE Pica",
      "Frieren: Beyond Journey's End",
      "Munecon",
      "Vinland Saga",
      "Saint Seiya",
      "Classroom of the Elite",
      "Boku no Pico",
      "Made in Abyss",
      "Doctores",
      "Naruto: Movies & Specials",
      "Gurren Lagann",
      "The Shannara Chronicles",
      "Noche Chamuco",
      "Psycho-Pass",
      "Game of Thrones",
      "Hunter x Hunter",
      "Fire Force",
      "The Eminence in Shadow",
      "Ergo Proxy",
      "Overlord",
      "Sofi Anime",
      "Saw",
      "It",
      "Gintama",
      "Ghost in the Shell",
      "Violet Evergarden",
      "Pelea Espadas",
      "Baki",
      "Mushoku Tensei: Movies & Specials",
      "One Piece: Live Action",
      "Food Wars! Shokugeki no Soma",
      "Monster",
      "Baki Hanma",
      "Entrenando Waifu: Movies & Specials",
      "Crossover Tortilla",
      "The Matrix",
      "Entrenando Waifu",
      "The Quintessential Quintuplets: Movies & Specials",
      "Fate/Grand Order: Movies & Specials",
      "Fate/strange Fake",
      "Fate/Grand Order - Absolute Demonic Front: Babylonia",
      "Anime Manuela",
      "Ending Party Ranking",
      "Fate/stay night: Movies & Specials",
      "Dragon Ball",
      "Dragon Ball Super: Movies & Specials",
      "Gintama: Movies & Specials",
      "Dragon Ball Super",
      "Mob Psycho 100",
      "Black Clover",
      "The Conjuring",
      "Pijamada Peliculas Terror: Movies & Specials",
      "Code Geass",
      "MI Abuelo VS Paloma Cerro",
      "Dragon Ball GT",
      "Fate/Zero",
      "Hajime no Ippo",
      "Fate/stay night",
      "Sword Art Online",
      "Dragon Ball Z",
      "Hajime no Ippo: Movies & Specials",
      "Amagi Brilliant Park",
      "Maquia: When the Promised Flower Blooms",
      "Chainsaw Man",
      "Yahari Ore no Seishun Love Comedy wa Machigatteiru.",
      "Calificando Ending",
      "Trapped in a Dating Sim: The World of Otome Games is Tough for Mobs",
      "Kuroko's Basketball",
      "So I'm a Spider, So What?",
      "Bleach",
      "Fullmetal Alchemist",
      "Ojos Rojos",
      "Dragon Ball: Movies & Specials",
      "The Familiar of Zero",
      "Cars",
      "Reparacion Congelador: Movies & Specials",
      "Weathering with You: Movies & Specials",
      "86",
      "Gato",
      "Spy x Family",
      "No Game No Life",
      "I Want to Eat Your Pancreas",
      "Cautious Hero: The Hero Is Overpowered but Overly Cautious",
      "Ao no Exorcist",
      "Wolf Children: Movies & Specials",
      "The Quintessential Quintuplets",
      "Goblin Slayer",
      "Attack on Titan",
      "DJ Poniendo Rolas Chidas",
      "Charlotte",
      "Betatester",
      "Jueves Random Riko SUS Panas: Movies & Specials",
      "Your Lie in April",
      "A Silent Voice",
      "Fairy Tail",
      "Guilty Crown",
      "Loca Pelirosa",
      "Secreto Montana",
      "Komi Can't Communicate",
      "Assassination Classroom",
      "Minecraft",
      "Fullmetal Alchemist: Movies & Specials",
      "Tokyo Revengers",
      "Welcome to Demon School! Iruma-kun",
      "Deadman Wonderland",
      "Fairy Tail: Movies & Specials",
      "Akame ga Kill",
      "Saga of Tanya the Evil",
      "One Punch Man",
      "Don't Toy with Me, Miss Nagatoro",
      "Votacion",
      "Kaguya-sama: Love Is War: Movies & Specials",
      "Dr. Stone",
      "Re:Zero − Starting Life in Another World",
      "Noche Juegos Terror Sofi"
    ],
    "populares_sofi_tv": [
      "Dragon Ball Z",
      "Dragon Ball Super",
      "Naruto",
      "Gintama",
      "Saint Seiya",
      "Dragon Ball GT",
      "The Seven Deadly Sins",
      "Hajime no Ippo",
      "Food Wars! Shokugeki no Soma",
      "Bleach",
      "The Seven Deadly Sins: Four Knights of the Apocalypse",
      "Dragon Ball",
      "Brokeback Mountain",
      "Hunter x Hunter",
      "Baki",
      "Fairy Tail",
      "Code Geass",
      "Haikyu!!",
      "Sword Art Online",
      "The Apothecary Diaries",
      "Avatar: The Last Airbender",
      "Amnesia Montana",
      "Dragon Ball Z: Movies & Specials",
      "DanMachi",
      "Steins;Gate",
      "Tsukimichi: Moonlit Fantasy",
      "La Casa de Papel",
      "Fire Force",
      "Overlord",
      "Neon Genesis Evangelion",
      "Mushoku Tensei",
      "Mob Psycho 100",
      "The Legend of Korra",
      "Uma Musume: Pretty Derby",
      "One Punch Man",
      "Classroom of the Elite",
      "Anime Manuela",
      "Bleach: Thousand-Year Blood War",
      "Kengan Ashura",
      "Farmeando Ando",
      "Frieren: Beyond Journey's End",
      "Gurren Lagann",
      "El Pajas",
      "Entrenando Waifu",
      "Capibara",
      "The Seven Deadly Sins: Movies & Specials",
      "KonoSuba",
      "One Piece",
      "Kuroko's Basketball",
      "Extensible",
      "Ranking of Kings",
      "Delicious in Dungeon",
      "Summertime Rendering",
      "Vinland Saga",
      "Noche Chamuco",
      "Sabado BOX",
      "Mashle",
      "Assassination Classroom",
      "Kill la Kill",
      "Fate/Grand Order - Absolute Demonic Front: Babylonia",
      "Dragon Ball: Movies & Specials",
      "Bleach: Movies & Specials",
      "Betatester",
      "Dragon Ball Super: Movies & Specials",
      "The Matrix",
      "Saw",
      "Dr. Stone",
      "JoJo's Bizarre Adventure",
      "Welcome to Demon School! Iruma-kun",
      "Bakemonogatari",
      "Boku no Pico",
      "Grand Blue Dreaming",
      "Psycho-Pass",
      "KonoSuba: Movies & Specials",
      "One Piece: Live Action",
      "The 100 Girlfriends Who Really, Really, Really, Really, Really Love You",
      "Edgy Grandota",
      "QUE Pica",
      "Fullmetal Alchemist",
      "Pelea Espadas",
      "Planeta Mexicano",
      "Baki Hanma",
      "Re:Zero − Starting Life in Another World",
      "The Eminence in Shadow",
      "Sofi Anime",
      "Death Note",
      "Ergo Proxy",
      "The Quintessential Quintuplets",
      "Made in Abyss",
      "Fate/stay night",
      "MonsterVerse",
      "Hellsing",
      "Yahari Ore no Seishun Love Comedy wa Machigatteiru.",
      "Alien",
      "The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat",
      "Crossover Tortilla",
      "Anime Jefa",
      "Jujutsu Kaisen",
      "Black Clover",
      "Rambo",
      "Digimon",
      "Cautious Hero: The Hero Is Overpowered but Overly Cautious",
      "Goblin Slayer",
      "Akame ga Kill",
      "NieR:Automata Ver1.1a",
      "Loca Pelirosa",
      "Cars",
      "Attack on Titan",
      "Tokyo Revengers",
      "Pijamada Peliculas Terror: Movies & Specials",
      "Your Lie in April",
      "Akiba Maid War",
      "Golden Time",
      "No Game No Life",
      "Marvel",
      "Sword Art Online: Movies & Specials",
      "Nisemonogatari",
      "Minecraft",
      "Fairy Tail: Movies & Specials",
      "Reparacion Congelador: Movies & Specials",
      "Doctores",
      "Amagi Brilliant Park",
      "Fate/Zero",
      "Gintama: Movies & Specials",
      "MI Abuelo VS Paloma Cerro",
      "Ojos Rojos",
      "Saga of Tanya the Evil",
      "Shangri-La Frontier",
      "El Pajas: Movies & Specials",
      "Spider-Man",
      "Trapped in a Dating Sim: The World of Otome Games is Tough for Mobs",
      "Fate/stay night: Movies & Specials",
      "Charlotte",
      "Fullmetal Alchemist: Movies & Specials",
      "The Conjuring",
      "K-ON",
      "Record of Ragnarok",
      "Votacion",
      "86",
      "Viejos Lesbianos VS Trasvestis Espaciales",
      "Extensible Navideno",
      "It",
      "Mamadas Seyr Esto SE Queda",
      "Mushoku Tensei: Movies & Specials",
      "Especial Howelin: Movies & Specials",
      "Kaiju No. 8",
      "Calificando Ending",
      "Spy x Family",
      "A Silent Voice",
      "Fate/strange Fake",
      "Primer IRL",
      "Game of Thrones",
      "Fate/Grand Order: Movies & Specials",
      "Ending Party Ranking",
      "Alya Sometimes Hides Her Feelings in Russian",
      "Extensible Casa Cartoon",
      "Blue Lock",
      "The Quintessential Quintuplets: Movies & Specials",
      "Megamind",
      "Munecon",
      "Ghost in the Shell",
      "Extensible Peliculas: Movies & Specials",
      "Entrenando Waifu: Movies & Specials",
      "Puella Magi Madoka Magica: Movies & Specials",
      "My Hero Academia",
      "The Shannara Chronicles",
      "Cumpleanos OWO",
      "Gato",
      "Naruto: Movies & Specials",
      "So I'm a Spider, So What?",
      "Haikyu!!: Movies & Specials",
      "Vemos Anime Jefri",
      "DJ Poniendo Rolas Chidas",
      "Hajime no Ippo: Movies & Specials",
      "Monster",
      "Violet Evergarden",
      "Don't Toy with Me, Miss Nagatoro",
      "Chainsaw Man",
      "Kong: Skull Island",
      "Uma Musume: Pretty Derby: Movies & Specials",
      "The Familiar of Zero",
      "Weathering with You: Movies & Specials",
      "Secreto Montana",
      "Sakamoto Days",
      "I Want to Eat Your Pancreas",
      "Komi Can't Communicate",
      "Ao no Exorcist",
      "Noche Juegos Terror Sofi",
      "Maquia: When the Promised Flower Blooms",
      "Jueves Random Riko SUS Panas: Movies & Specials",
      "Guilty Crown",
      "Rise of the Guardians",
      "My Dress-Up Darling",
      "Codigo Traje Rojo",
      "Jingle All the Way",
      "Knowing",
      "Monsters vs. Aliens",
      "Kaguya-sama: Love Is War: Movies & Specials",
      "Wolf Children: Movies & Specials",
      "Deadman Wonderland",
      "Mindhunter"
    ],
    "noche_de_peliculas": [
      "Dragon Ball Z: Movies & Specials",
      "The Seven Deadly Sins: Movies & Specials",
      "Dragon Ball: Movies & Specials",
      "Bleach: Movies & Specials",
      "Dragon Ball Super: Movies & Specials",
      "KonoSuba: Movies & Specials",
      "MonsterVerse",
      "Pijamada Peliculas Terror: Movies & Specials",
      "Marvel",
      "Sword Art Online: Movies & Specials",
      "Fairy Tail: Movies & Specials",
      "Reparacion Congelador: Movies & Specials",
      "Gintama: Movies & Specials",
      "El Pajas: Movies & Specials",
      "Spider-Man",
      "Fate/stay night: Movies & Specials",
      "Fullmetal Alchemist: Movies & Specials",
      "Mushoku Tensei: Movies & Specials",
      "Especial Howelin: Movies & Specials",
      "Fate/Grand Order: Movies & Specials",
      "The Quintessential Quintuplets: Movies & Specials",
      "Extensible Peliculas: Movies & Specials",
      "Entrenando Waifu: Movies & Specials",
      "Puella Magi Madoka Magica: Movies & Specials",
      "Naruto: Movies & Specials",
      "Haikyu!!: Movies & Specials",
      "Hajime no Ippo: Movies & Specials",
      "Uma Musume: Pretty Derby: Movies & Specials",
      "Weathering with You: Movies & Specials",
      "Jueves Random Riko SUS Panas: Movies & Specials",
      "Kaguya-sama: Love Is War: Movies & Specials",
      "Wolf Children: Movies & Specials",
      "Mindhunter"
    ],
    "top_anime_semana": [
      "Dragon Ball Super",
      "Naruto",
      "Gintama",
      "Saint Seiya",
      "One Piece",
      "Dragon Ball GT",
      "The Seven Deadly Sins",
      "Hajime no Ippo",
      "Food Wars! Shokugeki no Soma",
      "Bleach",
      "The Seven Deadly Sins: Four Knights of the Apocalypse",
      "Brokeback Mountain",
      "Hunter x Hunter",
      "Baki",
      "Code Geass",
      "Haikyu!!",
      "Record of Ragnarok",
      "Sword Art Online",
      "The Apothecary Diaries",
      "Avatar: The Last Airbender",
      "DanMachi",
      "Steins;Gate",
      "Tsukimichi: Moonlit Fantasy",
      "La Casa de Papel",
      "Fire Force",
      "Overlord",
      "Neon Genesis Evangelion",
      "Mushoku Tensei",
      "Mob Psycho 100",
      "The Legend of Korra",
      "Uma Musume: Pretty Derby",
      "One Punch Man",
      "Anime Manuela",
      "Bleach: Thousand-Year Blood War",
      "Kengan Ashura",
      "Farmeando Ando",
      "Gurren Lagann",
      "Entrenando Waifu",
      "Capibara",
      "KonoSuba",
      "Extensible",
      "Ranking of Kings",
      "Summertime Rendering",
      "Vinland Saga",
      "NieR:Automata Ver1.1a",
      "Grand Blue Dreaming",
      "Mashle",
      "Kill la Kill",
      "Fate/Grand Order - Absolute Demonic Front: Babylonia",
      "The Matrix",
      "Dr. Stone",
      "JoJo's Bizarre Adventure",
      "Bakemonogatari",
      "Psycho-Pass",
      "The 100 Girlfriends Who Really, Really, Really, Really, Really Love You",
      "Edgy Grandota",
      "Fullmetal Alchemist",
      "Pelea Espadas",
      "Baki Hanma",
      "Re:Zero − Starting Life in Another World",
      "The Eminence in Shadow",
      "Sofi Anime",
      "Ergo Proxy",
      "The Quintessential Quintuplets",
      "Made in Abyss",
      "Fate/stay night",
      "Hellsing",
      "Anime Jefa",
      "Jujutsu Kaisen",
      "Black Clover",
      "Rambo",
      "Cautious Hero: The Hero Is Overpowered but Overly Cautious",
      "Goblin Slayer",
      "Loca Pelirosa",
      "Attack on Titan",
      "Tokyo Revengers",
      "Akiba Maid War",
      "Nisemonogatari",
      "Minecraft",
      "Doctores",
      "Fate/Zero",
      "Ojos Rojos",
      "Shangri-La Frontier",
      "Charlotte",
      "86",
      "Spy x Family",
      "Game of Thrones",
      "Alya Sometimes Hides Her Feelings in Russian",
      "My Dress-Up Darling",
      "My Hero Academia",
      "The Shannara Chronicles",
      "Vemos Anime Jefri",
      "Monster",
      "Chainsaw Man",
      "The Familiar of Zero",
      "Secreto Montana",
      "Sakamoto Days",
      "Komi Can't Communicate",
      "Ao no Exorcist",
      "Deadman Wonderland",
      "Digimon",
      "K-ON"
    ]
  },
  "show_stats": {
    "86": {
      "id": "86",
      "name": "86",
      "kind": "anime",
      "latestTimestamp": 1651608784000,
      "totalViews": 27269,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "One Piece": {
      "id": "One Piece",
      "name": "One Piece",
      "kind": "anime",
      "latestTimestamp": 1767234614000,
      "totalViews": 607844,
      "viewsLast180d": 111377,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "The Seven Deadly Sins": {
      "id": "The Seven Deadly Sins",
      "name": "The Seven Deadly Sins",
      "kind": "anime",
      "latestTimestamp": 1740576113000,
      "totalViews": 502201,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "The Seven Deadly Sins: Movies & Specials": {
      "id": "The Seven Deadly Sins: Movies & Specials",
      "name": "The Seven Deadly Sins: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1743376686000,
      "totalViews": 115042,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Saint Seiya": {
      "id": "Saint Seiya",
      "name": "Saint Seiya",
      "kind": "anime",
      "latestTimestamp": 1713834740000,
      "totalViews": 610324,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "The Legend of Korra": {
      "id": "The Legend of Korra",
      "name": "The Legend of Korra",
      "kind": "anime",
      "latestTimestamp": 1768217480000,
      "totalViews": 154179,
      "viewsLast180d": 154179,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Naruto": {
      "id": "Naruto",
      "name": "Naruto",
      "kind": "anime",
      "latestTimestamp": 1733213611000,
      "totalViews": 670146,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Dragon Ball GT": {
      "id": "Dragon Ball GT",
      "name": "Dragon Ball GT",
      "kind": "anime",
      "latestTimestamp": 1682141432000,
      "totalViews": 580955,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Dragon Ball Super": {
      "id": "Dragon Ball Super",
      "name": "Dragon Ball Super",
      "kind": "anime",
      "latestTimestamp": 1688794111000,
      "totalViews": 1374573,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Uma Musume: Pretty Derby": {
      "id": "Uma Musume: Pretty Derby",
      "name": "Uma Musume: Pretty Derby",
      "kind": "anime",
      "latestTimestamp": 1772787114000,
      "totalViews": 150506,
      "viewsLast180d": 150506,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Food Wars! Shokugeki no Soma": {
      "id": "Food Wars! Shokugeki no Soma",
      "name": "Food Wars! Shokugeki no Soma",
      "kind": "anime",
      "latestTimestamp": 1696792328000,
      "totalViews": 438146,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Haikyu!!": {
      "id": "Haikyu!!",
      "name": "Haikyu!!",
      "kind": "anime",
      "latestTimestamp": 1737278507000,
      "totalViews": 231085,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Haikyu!!: Movies & Specials": {
      "id": "Haikyu!!: Movies & Specials",
      "name": "Haikyu!!: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1737965185000,
      "totalViews": 18739,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Gintama": {
      "id": "Gintama",
      "name": "Gintama",
      "kind": "anime",
      "latestTimestamp": 1700604015000,
      "totalViews": 655322,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Avatar: The Last Airbender": {
      "id": "Avatar: The Last Airbender",
      "name": "Avatar: The Last Airbender",
      "kind": "anime",
      "latestTimestamp": 1758532200000,
      "totalViews": 205852,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "NieR:Automata Ver1.1a": {
      "id": "NieR:Automata Ver1.1a",
      "name": "NieR:Automata Ver1.1a",
      "kind": "anime",
      "latestTimestamp": 1761203554000,
      "totalViews": 97873,
      "viewsLast180d": 45927,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Brokeback Mountain": {
      "id": "Brokeback Mountain",
      "name": "Brokeback Mountain",
      "kind": "anime",
      "latestTimestamp": 1750723968000,
      "totalViews": 269385,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "The Apothecary Diaries": {
      "id": "The Apothecary Diaries",
      "name": "The Apothecary Diaries",
      "kind": "anime",
      "latestTimestamp": 1754358127000,
      "totalViews": 207063,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "La Casa de Papel": {
      "id": "La Casa de Papel",
      "name": "La Casa de Papel",
      "kind": "anime",
      "latestTimestamp": 1728331291000,
      "totalViews": 173210,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Steins;Gate": {
      "id": "Steins;Gate",
      "name": "Steins;Gate",
      "kind": "anime",
      "latestTimestamp": 1725520648000,
      "totalViews": 184284,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Grand Blue Dreaming": {
      "id": "Grand Blue Dreaming",
      "name": "Grand Blue Dreaming",
      "kind": "anime",
      "latestTimestamp": 1764537746000,
      "totalViews": 92199,
      "viewsLast180d": 75673,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Summertime Rendering": {
      "id": "Summertime Rendering",
      "name": "Summertime Rendering",
      "kind": "anime",
      "latestTimestamp": 1758514424000,
      "totalViews": 102089,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Fire Force": {
      "id": "Fire Force",
      "name": "Fire Force",
      "kind": "anime",
      "latestTimestamp": 1705294676000,
      "totalViews": 167908,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Gurren Lagann": {
      "id": "Gurren Lagann",
      "name": "Gurren Lagann",
      "kind": "anime",
      "latestTimestamp": 1709780991000,
      "totalViews": 133228,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Bakemonogatari": {
      "id": "Bakemonogatari",
      "name": "Bakemonogatari",
      "kind": "anime",
      "latestTimestamp": 1757133215000,
      "totalViews": 75962,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Capibara": {
      "id": "Capibara",
      "name": "Capibara",
      "kind": "anime",
      "latestTimestamp": 1754359487000,
      "totalViews": 117094,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Entrenando Waifu": {
      "id": "Entrenando Waifu",
      "name": "Entrenando Waifu",
      "kind": "anime",
      "latestTimestamp": 1694864847000,
      "totalViews": 127492,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Mashle": {
      "id": "Mashle",
      "name": "Mashle",
      "kind": "anime",
      "latestTimestamp": 1726198891000,
      "totalViews": 90521,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Hellsing": {
      "id": "Hellsing",
      "name": "Hellsing",
      "kind": "anime",
      "latestTimestamp": 1766576319000,
      "totalViews": 55058,
      "viewsLast180d": 55058,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Hajime no Ippo": {
      "id": "Hajime no Ippo",
      "name": "Hajime no Ippo",
      "kind": "anime",
      "latestTimestamp": 1680459670000,
      "totalViews": 444028,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Tsukimichi: Moonlit Fantasy": {
      "id": "Tsukimichi: Moonlit Fantasy",
      "name": "Tsukimichi: Moonlit Fantasy",
      "kind": "anime",
      "latestTimestamp": 1751411651000,
      "totalViews": 179918,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Kill la Kill": {
      "id": "Kill la Kill",
      "name": "Kill la Kill",
      "kind": "anime",
      "latestTimestamp": 1756792284000,
      "totalViews": 89552,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Neon Genesis Evangelion": {
      "id": "Neon Genesis Evangelion",
      "name": "Neon Genesis Evangelion",
      "kind": "anime",
      "latestTimestamp": 1744336285000,
      "totalViews": 158915,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Vinland Saga": {
      "id": "Vinland Saga",
      "name": "Vinland Saga",
      "kind": "anime",
      "latestTimestamp": 1713979522000,
      "totalViews": 99759,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Baki": {
      "id": "Baki",
      "name": "Baki",
      "kind": "anime",
      "latestTimestamp": 1697459311000,
      "totalViews": 253309,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Code Geass": {
      "id": "Code Geass",
      "name": "Code Geass",
      "kind": "anime",
      "latestTimestamp": 1686024019000,
      "totalViews": 233260,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "The Seven Deadly Sins: Four Knights of the Apocalypse": {
      "id": "The Seven Deadly Sins: Four Knights of the Apocalypse",
      "name": "The Seven Deadly Sins: Four Knights of the Apocalypse",
      "kind": "anime",
      "latestTimestamp": 1748403815000,
      "totalViews": 285575,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Psycho-Pass": {
      "id": "Psycho-Pass",
      "name": "Psycho-Pass",
      "kind": "anime",
      "latestTimestamp": 1707056401000,
      "totalViews": 74923,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "DanMachi": {
      "id": "DanMachi",
      "name": "DanMachi",
      "kind": "anime",
      "latestTimestamp": 1732593471000,
      "totalViews": 184817,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Dr. Stone": {
      "id": "Dr. Stone",
      "name": "Dr. Stone",
      "kind": "anime",
      "latestTimestamp": 1621699198000,
      "totalViews": 77981,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "The 100 Girlfriends Who Really, Really, Really, Really, Really Love You": {
      "id": "The 100 Girlfriends Who Really, Really, Really, Really, Really Love You",
      "name": "The 100 Girlfriends Who Really, Really, Really, Really, Really Love You",
      "kind": "anime",
      "latestTimestamp": 1753859980000,
      "totalViews": 72096,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "The Matrix": {
      "id": "The Matrix",
      "name": "The Matrix",
      "kind": "anime",
      "latestTimestamp": 1695133655000,
      "totalViews": 81390,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Re:Zero − Starting Life in Another World": {
      "id": "Re:Zero − Starting Life in Another World",
      "name": "Re:Zero − Starting Life in Another World",
      "kind": "anime",
      "latestTimestamp": 1618192721000,
      "totalViews": 60791,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Shangri-La Frontier": {
      "id": "Shangri-La Frontier",
      "name": "Shangri-La Frontier",
      "kind": "anime",
      "latestTimestamp": 1769938714000,
      "totalViews": 31602,
      "viewsLast180d": 31602,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Akiba Maid War": {
      "id": "Akiba Maid War",
      "name": "Akiba Maid War",
      "kind": "anime",
      "latestTimestamp": 1758789998000,
      "totalViews": 41212,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Anime Manuela": {
      "id": "Anime Manuela",
      "name": "Anime Manuela",
      "kind": "anime",
      "latestTimestamp": 1690868594000,
      "totalViews": 140848,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Mushoku Tensei": {
      "id": "Mushoku Tensei",
      "name": "Mushoku Tensei",
      "kind": "anime",
      "latestTimestamp": 1721349027000,
      "totalViews": 154884,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Mushoku Tensei: Movies & Specials": {
      "id": "Mushoku Tensei: Movies & Specials",
      "name": "Mushoku Tensei: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1697411947000,
      "totalViews": 26078,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Ergo Proxy": {
      "id": "Ergo Proxy",
      "name": "Ergo Proxy",
      "kind": "anime",
      "latestTimestamp": 1704215446000,
      "totalViews": 59633,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Goblin Slayer": {
      "id": "Goblin Slayer",
      "name": "Goblin Slayer",
      "kind": "anime",
      "latestTimestamp": 1644936395000,
      "totalViews": 47625,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Farmeando Ando": {
      "id": "Farmeando Ando",
      "name": "Farmeando Ando",
      "kind": "anime",
      "latestTimestamp": 1747177491000,
      "totalViews": 139234,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "KonoSuba": {
      "id": "KonoSuba",
      "name": "KonoSuba",
      "kind": "anime",
      "latestTimestamp": 1749526397000,
      "totalViews": 114295,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Ranking of Kings": {
      "id": "Ranking of Kings",
      "name": "Ranking of Kings",
      "kind": "anime",
      "latestTimestamp": 1720232096000,
      "totalViews": 105438,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Nisemonogatari": {
      "id": "Nisemonogatari",
      "name": "Nisemonogatari",
      "kind": "anime",
      "latestTimestamp": 1760583874000,
      "totalViews": 38336,
      "viewsLast180d": 38336,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "One Piece: Live Action": {
      "id": "One Piece: Live Action",
      "name": "One Piece: Live Action",
      "kind": "series",
      "latestTimestamp": 1697264325000,
      "totalViews": 72887,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Overlord": {
      "id": "Overlord",
      "name": "Overlord",
      "kind": "anime",
      "latestTimestamp": 1703075621000,
      "totalViews": 159761,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Vemos Anime Jefri": {
      "id": "Vemos Anime Jefri",
      "name": "Vemos Anime Jefri",
      "kind": "anime",
      "latestTimestamp": 1728958455000,
      "totalViews": 18606,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Made in Abyss": {
      "id": "Made in Abyss",
      "name": "Made in Abyss",
      "kind": "anime",
      "latestTimestamp": 1711064951000,
      "totalViews": 58120,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Black Clover": {
      "id": "Black Clover",
      "name": "Black Clover",
      "kind": "anime",
      "latestTimestamp": 1688099994000,
      "totalViews": 50603,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "My Hero Academia": {
      "id": "My Hero Academia",
      "name": "My Hero Academia",
      "kind": "anime",
      "latestTimestamp": 1768425218000,
      "totalViews": 20473,
      "viewsLast180d": 20473,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Tokyo Revengers": {
      "id": "Tokyo Revengers",
      "name": "Tokyo Revengers",
      "kind": "anime",
      "latestTimestamp": 1632916774000,
      "totalViews": 43162,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Digimon": {
      "id": "Digimon",
      "name": "Digimon",
      "kind": "anime",
      "latestTimestamp": 1774258796000,
      "totalViews": 49514,
      "viewsLast180d": 49514,
      "viewsLast7d": 4571,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Doctores": {
      "id": "Doctores",
      "name": "Doctores",
      "kind": "anime",
      "latestTimestamp": 1710684575000,
      "totalViews": 37378,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Edgy Grandota": {
      "id": "Edgy Grandota",
      "name": "Edgy Grandota",
      "kind": "anime",
      "latestTimestamp": 1721265188000,
      "totalViews": 70998,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Attack on Titan": {
      "id": "Attack on Titan",
      "name": "Attack on Titan",
      "kind": "anime",
      "latestTimestamp": 1644792916000,
      "totalViews": 44125,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Spy x Family": {
      "id": "Spy x Family",
      "name": "Spy x Family",
      "kind": "anime",
      "latestTimestamp": 1650832118000,
      "totalViews": 25358,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Fate/stay night": {
      "id": "Fate/stay night",
      "name": "Fate/stay night",
      "kind": "anime",
      "latestTimestamp": 1679031794000,
      "totalViews": 57889,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "JoJo's Bizarre Adventure": {
      "id": "JoJo's Bizarre Adventure",
      "name": "JoJo's Bizarre Adventure",
      "kind": "anime",
      "latestTimestamp": 1735248466000,
      "totalViews": 77877,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Kengan Ashura": {
      "id": "Kengan Ashura",
      "name": "Kengan Ashura",
      "kind": "anime",
      "latestTimestamp": 1728025690000,
      "totalViews": 140455,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Sword Art Online": {
      "id": "Sword Art Online",
      "name": "Sword Art Online",
      "kind": "anime",
      "latestTimestamp": 1678401804000,
      "totalViews": 216741,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Ojos Rojos": {
      "id": "Ojos Rojos",
      "name": "Ojos Rojos",
      "kind": "anime",
      "latestTimestamp": 1656825941000,
      "totalViews": 34430,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "The Quintessential Quintuplets": {
      "id": "The Quintessential Quintuplets",
      "name": "The Quintessential Quintuplets",
      "kind": "anime",
      "latestTimestamp": 1645190653000,
      "totalViews": 59409,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Pelea Espadas": {
      "id": "Pelea Espadas",
      "name": "Pelea Espadas",
      "kind": "anime",
      "latestTimestamp": 1698712283000,
      "totalViews": 65283,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Bleach: Thousand-Year Blood War": {
      "id": "Bleach: Thousand-Year Blood War",
      "name": "Bleach: Thousand-Year Blood War",
      "kind": "anime",
      "latestTimestamp": 1736877193000,
      "totalViews": 140758,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Sakamoto Days": {
      "id": "Sakamoto Days",
      "name": "Sakamoto Days",
      "kind": "anime",
      "latestTimestamp": 1769585808000,
      "totalViews": 15153,
      "viewsLast180d": 15153,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Baki Hanma": {
      "id": "Baki Hanma",
      "name": "Baki Hanma",
      "kind": "anime",
      "latestTimestamp": 1695701270000,
      "totalViews": 64803,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "The Eminence in Shadow": {
      "id": "The Eminence in Shadow",
      "name": "The Eminence in Shadow",
      "kind": "anime",
      "latestTimestamp": 1704665669000,
      "totalViews": 60183,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Record of Ragnarok": {
      "id": "Record of Ragnarok",
      "name": "Record of Ragnarok",
      "kind": "anime",
      "latestTimestamp": 1765851827000,
      "totalViews": 230115,
      "viewsLast180d": 27784,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Sofi Anime": {
      "id": "Sofi Anime",
      "name": "Sofi Anime",
      "kind": "anime",
      "latestTimestamp": 1701201027000,
      "totalViews": 60162,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "My Dress-Up Darling": {
      "id": "My Dress-Up Darling",
      "name": "My Dress-Up Darling",
      "kind": "anime",
      "latestTimestamp": 1770864525000,
      "totalViews": 23492,
      "viewsLast180d": 12012,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Anime Jefa": {
      "id": "Anime Jefa",
      "name": "Anime Jefa",
      "kind": "anime",
      "latestTimestamp": 1738643135000,
      "totalViews": 52021,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Fullmetal Alchemist": {
      "id": "Fullmetal Alchemist",
      "name": "Fullmetal Alchemist",
      "kind": "anime",
      "latestTimestamp": 1658095522000,
      "totalViews": 68301,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Bleach": {
      "id": "Bleach",
      "name": "Bleach",
      "kind": "anime",
      "latestTimestamp": 1659211153000,
      "totalViews": 409350,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Marvel": {
      "id": "Marvel",
      "name": "Marvel",
      "kind": "movie",
      "latestTimestamp": 1774256806000,
      "totalViews": 482177,
      "viewsLast180d": 39124,
      "viewsLast7d": 3603,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Charlotte": {
      "id": "Charlotte",
      "name": "Charlotte",
      "kind": "anime",
      "latestTimestamp": 1642568661000,
      "totalViews": 29860,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "The Shannara Chronicles": {
      "id": "The Shannara Chronicles",
      "name": "The Shannara Chronicles",
      "kind": "anime",
      "latestTimestamp": 1709594539000,
      "totalViews": 20455,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Deadman Wonderland": {
      "id": "Deadman Wonderland",
      "name": "Deadman Wonderland",
      "kind": "anime",
      "latestTimestamp": 1630191941000,
      "totalViews": 9762,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Fate/Grand Order - Absolute Demonic Front: Babylonia": {
      "id": "Fate/Grand Order - Absolute Demonic Front: Babylonia",
      "name": "Fate/Grand Order - Absolute Demonic Front: Babylonia",
      "kind": "anime",
      "latestTimestamp": 1692030268000,
      "totalViews": 89436,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Ao no Exorcist": {
      "id": "Ao no Exorcist",
      "name": "Ao no Exorcist",
      "kind": "anime",
      "latestTimestamp": 1646998359000,
      "totalViews": 13782,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Extensible": {
      "id": "Extensible",
      "name": "Extensible",
      "kind": "anime",
      "latestTimestamp": 1741843738000,
      "totalViews": 106676,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Fate/Zero": {
      "id": "Fate/Zero",
      "name": "Fate/Zero",
      "kind": "anime",
      "latestTimestamp": 1680533401000,
      "totalViews": 35801,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Game of Thrones": {
      "id": "Game of Thrones",
      "name": "Game of Thrones",
      "kind": "anime",
      "latestTimestamp": 1707054644000,
      "totalViews": 24236,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Cautious Hero: The Hero Is Overpowered but Overly Cautious": {
      "id": "Cautious Hero: The Hero Is Overpowered but Overly Cautious",
      "name": "Cautious Hero: The Hero Is Overpowered but Overly Cautious",
      "kind": "anime",
      "latestTimestamp": 1647188939000,
      "totalViews": 48358,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Hunter x Hunter": {
      "id": "Hunter x Hunter",
      "name": "Hunter x Hunter",
      "kind": "anime",
      "latestTimestamp": 1705644825000,
      "totalViews": 266927,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Jujutsu Kaisen": {
      "id": "Jujutsu Kaisen",
      "name": "Jujutsu Kaisen",
      "kind": "anime",
      "latestTimestamp": 1728773699000,
      "totalViews": 50744,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Loca Pelirosa": {
      "id": "Loca Pelirosa",
      "name": "Loca Pelirosa",
      "kind": "anime",
      "latestTimestamp": 1636637373000,
      "totalViews": 45421,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "The Familiar of Zero": {
      "id": "The Familiar of Zero",
      "name": "The Familiar of Zero",
      "kind": "anime",
      "latestTimestamp": 1656344427000,
      "totalViews": 15644,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Minecraft": {
      "id": "Minecraft",
      "name": "Minecraft",
      "kind": "anime",
      "latestTimestamp": 1633895200000,
      "totalViews": 38174,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Mob Psycho 100": {
      "id": "Mob Psycho 100",
      "name": "Mob Psycho 100",
      "kind": "anime",
      "latestTimestamp": 1688520667000,
      "totalViews": 154339,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Monster": {
      "id": "Monster",
      "name": "Monster",
      "kind": "anime",
      "latestTimestamp": 1696103818000,
      "totalViews": 18273,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Naruto: Movies & Specials": {
      "id": "Naruto: Movies & Specials",
      "name": "Naruto: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1710683863000,
      "totalViews": 19076,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Komi Can't Communicate": {
      "id": "Komi Can't Communicate",
      "name": "Komi Can't Communicate",
      "kind": "anime",
      "latestTimestamp": 1634156680000,
      "totalViews": 14237,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "One Punch Man": {
      "id": "One Punch Man",
      "name": "One Punch Man",
      "kind": "anime",
      "latestTimestamp": 1627250285000,
      "totalViews": 142970,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Chainsaw Man": {
      "id": "Chainsaw Man",
      "name": "Chainsaw Man",
      "kind": "anime",
      "latestTimestamp": 1665520956000,
      "totalViews": 17438,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Rambo": {
      "id": "Rambo",
      "name": "Rambo",
      "kind": "anime",
      "latestTimestamp": 1741322321000,
      "totalViews": 50366,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Alya Sometimes Hides Her Feelings in Russian": {
      "id": "Alya Sometimes Hides Her Feelings in Russian",
      "name": "Alya Sometimes Hides Her Feelings in Russian",
      "kind": "anime",
      "latestTimestamp": 1726634921000,
      "totalViews": 23521,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Secreto Montana": {
      "id": "Secreto Montana",
      "name": "Secreto Montana",
      "kind": "anime",
      "latestTimestamp": 1636408816000,
      "totalViews": 15155,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Uma Musume: Pretty Derby: Movies & Specials": {
      "id": "Uma Musume: Pretty Derby: Movies & Specials",
      "name": "Uma Musume: Pretty Derby: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1769331347000,
      "totalViews": 16359,
      "viewsLast180d": 16359,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "K-ON": {
      "id": "K-ON",
      "name": "K-ON",
      "kind": "anime",
      "latestTimestamp": 1774261498000,
      "totalViews": 27979,
      "viewsLast180d": 27979,
      "viewsLast7d": 3953,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Spider-Man": {
      "id": "Spider-Man",
      "name": "Spider-Man",
      "kind": "movie",
      "latestTimestamp": 1772418870000,
      "totalViews": 70779,
      "viewsLast180d": 30747,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "KonoSuba: Movies & Specials": {
      "id": "KonoSuba: Movies & Specials",
      "name": "KonoSuba: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1749937750000,
      "totalViews": 73723,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Fate/Grand Order: Movies & Specials": {
      "id": "Fate/Grand Order: Movies & Specials",
      "name": "Fate/Grand Order: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1693345473000,
      "totalViews": 23685,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Extensible Peliculas: Movies & Specials": {
      "id": "Extensible Peliculas: Movies & Specials",
      "name": "Extensible Peliculas: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1719645676000,
      "totalViews": 21232,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Hajime no Ippo: Movies & Specials": {
      "id": "Hajime no Ippo: Movies & Specials",
      "name": "Hajime no Ippo: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1675037079000,
      "totalViews": 18349,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "El Pajas: Movies & Specials": {
      "id": "El Pajas: Movies & Specials",
      "name": "El Pajas: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1744952167000,
      "totalViews": 30773,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Mindhunter": {
      "id": "Mindhunter",
      "name": "Mindhunter",
      "kind": "movie",
      "latestTimestamp": 1769941134000,
      "totalViews": 6468,
      "viewsLast180d": 6468,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "The Quintessential Quintuplets: Movies & Specials": {
      "id": "The Quintessential Quintuplets: Movies & Specials",
      "name": "The Quintessential Quintuplets: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1694170476000,
      "totalViews": 22868,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Sword Art Online: Movies & Specials": {
      "id": "Sword Art Online: Movies & Specials",
      "name": "Sword Art Online: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1723183356000,
      "totalViews": 39116,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "MonsterVerse": {
      "id": "MonsterVerse",
      "name": "MonsterVerse",
      "kind": "movie",
      "latestTimestamp": 1765243109000,
      "totalViews": 56492,
      "viewsLast180d": 56492,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Dragon Ball: Movies & Specials": {
      "id": "Dragon Ball: Movies & Specials",
      "name": "Dragon Ball: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1656652817000,
      "totalViews": 88286,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Dragon Ball Z": {
      "id": "Dragon Ball Z",
      "name": "Dragon Ball Z",
      "kind": "live",
      "latestTimestamp": 1676703553000,
      "totalViews": 2542179,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Dragon Ball Z: Movies & Specials": {
      "id": "Dragon Ball Z: Movies & Specials",
      "name": "Dragon Ball Z: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1727817260000,
      "totalViews": 186211,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Dragon Ball Super: Movies & Specials": {
      "id": "Dragon Ball Super: Movies & Specials",
      "name": "Dragon Ball Super: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1690028872000,
      "totalViews": 81818,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Bleach: Movies & Specials": {
      "id": "Bleach: Movies & Specials",
      "name": "Bleach: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1728408867000,
      "totalViews": 86387,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Fairy Tail": {
      "id": "Fairy Tail",
      "name": "Fairy Tail",
      "kind": "live",
      "latestTimestamp": 1637423085000,
      "totalViews": 239147,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Fairy Tail: Movies & Specials": {
      "id": "Fairy Tail: Movies & Specials",
      "name": "Fairy Tail: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1630171879000,
      "totalViews": 37562,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Kuroko's Basketball": {
      "id": "Kuroko's Basketball",
      "name": "Kuroko's Basketball",
      "kind": "live",
      "latestTimestamp": 1661132407000,
      "totalViews": 108719,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Amnesia Montana": {
      "id": "Amnesia Montana",
      "name": "Amnesia Montana",
      "kind": "live",
      "latestTimestamp": 1748471854000,
      "totalViews": 196841,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Assassination Classroom": {
      "id": "Assassination Classroom",
      "name": "Assassination Classroom",
      "kind": "live",
      "latestTimestamp": 1634074915000,
      "totalViews": 90469,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Betatester": {
      "id": "Betatester",
      "name": "Betatester",
      "kind": "live",
      "latestTimestamp": 1642365566000,
      "totalViews": 85016,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Gintama: Movies & Specials": {
      "id": "Gintama: Movies & Specials",
      "name": "Gintama: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1689940594000,
      "totalViews": 34974,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Welcome to Demon School! Iruma-kun": {
      "id": "Welcome to Demon School! Iruma-kun",
      "name": "Welcome to Demon School! Iruma-kun",
      "kind": "live",
      "latestTimestamp": 1632669314000,
      "totalViews": 77486,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Noche Chamuco": {
      "id": "Noche Chamuco",
      "name": "Noche Chamuco",
      "kind": "live",
      "latestTimestamp": 1708966883000,
      "totalViews": 97229,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Yahari Ore no Seishun Love Comedy wa Machigatteiru.": {
      "id": "Yahari Ore no Seishun Love Comedy wa Machigatteiru.",
      "name": "Yahari Ore no Seishun Love Comedy wa Machigatteiru.",
      "kind": "live",
      "latestTimestamp": 1664305372000,
      "totalViews": 54490,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Classroom of the Elite": {
      "id": "Classroom of the Elite",
      "name": "Classroom of the Elite",
      "kind": "live",
      "latestTimestamp": 1713549019000,
      "totalViews": 142353,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Saw": {
      "id": "Saw",
      "name": "Saw",
      "kind": "live",
      "latestTimestamp": 1700875498000,
      "totalViews": 78483,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Amagi Brilliant Park": {
      "id": "Amagi Brilliant Park",
      "name": "Amagi Brilliant Park",
      "kind": "live",
      "latestTimestamp": 1670096637000,
      "totalViews": 35930,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Akame ga Kill": {
      "id": "Akame ga Kill",
      "name": "Akame ga Kill",
      "kind": "live",
      "latestTimestamp": 1628949480000,
      "totalViews": 46611,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat": {
      "id": "The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat",
      "name": "The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat",
      "kind": "live",
      "latestTimestamp": 1734034130000,
      "totalViews": 54043,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Saga of Tanya the Evil": {
      "id": "Saga of Tanya the Evil",
      "name": "Saga of Tanya the Evil",
      "kind": "live",
      "latestTimestamp": 1628121251000,
      "totalViews": 32160,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Your Lie in April": {
      "id": "Your Lie in April",
      "name": "Your Lie in April",
      "kind": "live",
      "latestTimestamp": 1641091158000,
      "totalViews": 41979,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "QUE Pica": {
      "id": "QUE Pica",
      "name": "QUE Pica",
      "kind": "live",
      "latestTimestamp": 1718237693000,
      "totalViews": 68973,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Cars": {
      "id": "Cars",
      "name": "Cars",
      "kind": "live",
      "latestTimestamp": 1655648344000,
      "totalViews": 45053,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Votacion": {
      "id": "Votacion",
      "name": "Votacion",
      "kind": "live",
      "latestTimestamp": 1624830751000,
      "totalViews": 27274,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "So I'm a Spider, So What?": {
      "id": "So I'm a Spider, So What?",
      "name": "So I'm a Spider, So What?",
      "kind": "live",
      "latestTimestamp": 1659971447000,
      "totalViews": 18968,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Delicious in Dungeon": {
      "id": "Delicious in Dungeon",
      "name": "Delicious in Dungeon",
      "kind": "live",
      "latestTimestamp": 1745280306000,
      "totalViews": 105023,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Calificando Ending": {
      "id": "Calificando Ending",
      "name": "Calificando Ending",
      "kind": "live",
      "latestTimestamp": 1663477141000,
      "totalViews": 25512,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Puella Magi Madoka Magica: Movies & Specials": {
      "id": "Puella Magi Madoka Magica: Movies & Specials",
      "name": "Puella Magi Madoka Magica: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1720234309000,
      "totalViews": 20945,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "The Conjuring": {
      "id": "The Conjuring",
      "name": "The Conjuring",
      "kind": "live",
      "latestTimestamp": 1686625234000,
      "totalViews": 28798,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Cumpleanos OWO": {
      "id": "Cumpleanos OWO",
      "name": "Cumpleanos OWO",
      "kind": "live",
      "latestTimestamp": 1728718109000,
      "totalViews": 20359,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Fate/strange Fake": {
      "id": "Fate/strange Fake",
      "name": "Fate/strange Fake",
      "kind": "live",
      "latestTimestamp": 1693193541000,
      "totalViews": 24919,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Ending Party Ranking": {
      "id": "Ending Party Ranking",
      "name": "Ending Party Ranking",
      "kind": "live",
      "latestTimestamp": 1690556102000,
      "totalViews": 23669,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Entrenando Waifu: Movies & Specials": {
      "id": "Entrenando Waifu: Movies & Specials",
      "name": "Entrenando Waifu: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1695497787000,
      "totalViews": 21190,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Fate/stay night: Movies & Specials": {
      "id": "Fate/stay night: Movies & Specials",
      "name": "Fate/stay night: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1690177714000,
      "totalViews": 30107,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Fullmetal Alchemist: Movies & Specials": {
      "id": "Fullmetal Alchemist: Movies & Specials",
      "name": "Fullmetal Alchemist: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1632941827000,
      "totalViews": 29431,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Gato": {
      "id": "Gato",
      "name": "Gato",
      "kind": "live",
      "latestTimestamp": 1651377488000,
      "totalViews": 19643,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Ghost in the Shell": {
      "id": "Ghost in the Shell",
      "name": "Ghost in the Shell",
      "kind": "live",
      "latestTimestamp": 1699916490000,
      "totalViews": 21459,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "It": {
      "id": "It",
      "name": "It",
      "kind": "live",
      "latestTimestamp": 1700611033000,
      "totalViews": 26566,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Jueves Random Riko SUS Panas: Movies & Specials": {
      "id": "Jueves Random Riko SUS Panas: Movies & Specials",
      "name": "Jueves Random Riko SUS Panas: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1641526976000,
      "totalViews": 13155,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "MI Abuelo VS Paloma Cerro": {
      "id": "MI Abuelo VS Paloma Cerro",
      "name": "MI Abuelo VS Paloma Cerro",
      "kind": "live",
      "latestTimestamp": 1685688048000,
      "totalViews": 34501,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Munecon": {
      "id": "Munecon",
      "name": "Munecon",
      "kind": "live",
      "latestTimestamp": 1714681467000,
      "totalViews": 21483,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Don't Toy with Me, Miss Nagatoro": {
      "id": "Don't Toy with Me, Miss Nagatoro",
      "name": "Don't Toy with Me, Miss Nagatoro",
      "kind": "live",
      "latestTimestamp": 1627104546000,
      "totalViews": 18034,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Wolf Children: Movies & Specials": {
      "id": "Wolf Children: Movies & Specials",
      "name": "Wolf Children: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1646366252000,
      "totalViews": 9825,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "No Game No Life": {
      "id": "No Game No Life",
      "name": "No Game No Life",
      "kind": "live",
      "latestTimestamp": 1648906812000,
      "totalViews": 40177,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Noche Juegos Terror Sofi": {
      "id": "Noche Juegos Terror Sofi",
      "name": "Noche Juegos Terror Sofi",
      "kind": "live",
      "latestTimestamp": 1617042876000,
      "totalViews": 13553,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Trapped in a Dating Sim: The World of Otome Games is Tough for Mobs": {
      "id": "Trapped in a Dating Sim: The World of Otome Games is Tough for Mobs",
      "name": "Trapped in a Dating Sim: The World of Otome Games is Tough for Mobs",
      "kind": "live",
      "latestTimestamp": 1663333678000,
      "totalViews": 30178,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "El Pajas": {
      "id": "El Pajas",
      "name": "El Pajas",
      "kind": "live",
      "latestTimestamp": 1748042285000,
      "totalViews": 131484,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Pijamada Peliculas Terror: Movies & Specials": {
      "id": "Pijamada Peliculas Terror: Movies & Specials",
      "name": "Pijamada Peliculas Terror: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1686333800000,
      "totalViews": 42509,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Primer IRL": {
      "id": "Primer IRL",
      "name": "Primer IRL",
      "kind": "live",
      "latestTimestamp": 1753932990000,
      "totalViews": 24493,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "I Want to Eat Your Pancreas": {
      "id": "I Want to Eat Your Pancreas",
      "name": "I Want to Eat Your Pancreas",
      "kind": "live",
      "latestTimestamp": 1647690301000,
      "totalViews": 14922,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Reparacion Congelador: Movies & Specials": {
      "id": "Reparacion Congelador: Movies & Specials",
      "name": "Reparacion Congelador: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1654228270000,
      "totalViews": 37451,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Weathering with You: Movies & Specials": {
      "id": "Weathering with You: Movies & Specials",
      "name": "Weathering with You: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1652459957000,
      "totalViews": 15273,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Kaguya-sama: Love Is War: Movies & Specials": {
      "id": "Kaguya-sama: Love Is War: Movies & Specials",
      "name": "Kaguya-sama: Love Is War: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1623447813000,
      "totalViews": 10626,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "A Silent Voice": {
      "id": "A Silent Voice",
      "name": "A Silent Voice",
      "kind": "live",
      "latestTimestamp": 1639256809000,
      "totalViews": 25076,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Frieren: Beyond Journey's End": {
      "id": "Frieren: Beyond Journey's End",
      "name": "Frieren: Beyond Journey's End",
      "kind": "other",
      "latestTimestamp": 1715651869000,
      "totalViews": 137093,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Death Note": {
      "id": "Death Note",
      "name": "Death Note",
      "kind": "other",
      "latestTimestamp": 1725216082000,
      "totalViews": 60138,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Sabado BOX": {
      "id": "Sabado BOX",
      "name": "Sabado BOX",
      "kind": "other",
      "latestTimestamp": 1731226300000,
      "totalViews": 94151,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Boku no Pico": {
      "id": "Boku no Pico",
      "name": "Boku no Pico",
      "kind": "other",
      "latestTimestamp": 1712294943000,
      "totalViews": 75875,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Planeta Mexicano": {
      "id": "Planeta Mexicano",
      "name": "Planeta Mexicano",
      "kind": "other",
      "latestTimestamp": 1725865003000,
      "totalViews": 65026,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Alien": {
      "id": "Alien",
      "name": "Alien",
      "kind": "other",
      "latestTimestamp": 1742953130000,
      "totalViews": 54445,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "DJ Poniendo Rolas Chidas": {
      "id": "DJ Poniendo Rolas Chidas",
      "name": "DJ Poniendo Rolas Chidas",
      "kind": "other",
      "latestTimestamp": 1643570432000,
      "totalViews": 18522,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Kaiju No. 8": {
      "id": "Kaiju No. 8",
      "name": "Kaiju No. 8",
      "kind": "other",
      "latestTimestamp": 1722911243000,
      "totalViews": 25622,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Codigo Traje Rojo": {
      "id": "Codigo Traje Rojo",
      "name": "Codigo Traje Rojo",
      "kind": "other",
      "latestTimestamp": 1766918815000,
      "totalViews": 11555,
      "viewsLast180d": 11555,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Crossover Tortilla": {
      "id": "Crossover Tortilla",
      "name": "Crossover Tortilla",
      "kind": "other",
      "latestTimestamp": 1695402572000,
      "totalViews": 52382,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Especial Howelin: Movies & Specials": {
      "id": "Especial Howelin: Movies & Specials",
      "name": "Especial Howelin: Movies & Specials",
      "kind": "movie",
      "latestTimestamp": 1730094981000,
      "totalViews": 25622,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Extensible Casa Cartoon": {
      "id": "Extensible Casa Cartoon",
      "name": "Extensible Casa Cartoon",
      "kind": "other",
      "latestTimestamp": 1719600474000,
      "totalViews": 23488,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Extensible Navideno": {
      "id": "Extensible Navideno",
      "name": "Extensible Navideno",
      "kind": "other",
      "latestTimestamp": 1735494066000,
      "totalViews": 26811,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Guilty Crown": {
      "id": "Guilty Crown",
      "name": "Guilty Crown",
      "kind": "other",
      "latestTimestamp": 1637360713000,
      "totalViews": 13096,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Kong: Skull Island": {
      "id": "Kong: Skull Island",
      "name": "Kong: Skull Island",
      "kind": "other",
      "latestTimestamp": 1757387591000,
      "totalViews": 17403,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Mamadas Seyr Esto SE Queda": {
      "id": "Mamadas Seyr Esto SE Queda",
      "name": "Mamadas Seyr Esto SE Queda",
      "kind": "other",
      "latestTimestamp": 1745180388000,
      "totalViews": 26296,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Maquia: When the Promised Flower Blooms": {
      "id": "Maquia: When the Promised Flower Blooms",
      "name": "Maquia: When the Promised Flower Blooms",
      "kind": "other",
      "latestTimestamp": 1668881069000,
      "totalViews": 13210,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Megamind": {
      "id": "Megamind",
      "name": "Megamind",
      "kind": "other",
      "latestTimestamp": 1756790132000,
      "totalViews": 22843,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Blue Lock": {
      "id": "Blue Lock",
      "name": "Blue Lock",
      "kind": "other",
      "latestTimestamp": 1754014261000,
      "totalViews": 22969,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Monsters vs. Aliens": {
      "id": "Monsters vs. Aliens",
      "name": "Monsters vs. Aliens",
      "kind": "other",
      "latestTimestamp": 1768175003000,
      "totalViews": 10636,
      "viewsLast180d": 10636,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Rise of the Guardians": {
      "id": "Rise of the Guardians",
      "name": "Rise of the Guardians",
      "kind": "other",
      "latestTimestamp": 1766634657000,
      "totalViews": 12303,
      "viewsLast180d": 12303,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Knowing": {
      "id": "Knowing",
      "name": "Knowing",
      "kind": "other",
      "latestTimestamp": 1762415164000,
      "totalViews": 11234,
      "viewsLast180d": 11234,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Dragon Ball": {
      "id": "Dragon Ball",
      "name": "Dragon Ball",
      "kind": "other",
      "latestTimestamp": 1690140793000,
      "totalViews": 273181,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Jingle All the Way": {
      "id": "Jingle All the Way",
      "name": "Jingle All the Way",
      "kind": "other",
      "latestTimestamp": 1766317579000,
      "totalViews": 11344,
      "viewsLast180d": 11344,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Golden Time": {
      "id": "Golden Time",
      "name": "Golden Time",
      "kind": "other",
      "latestTimestamp": 1747889014000,
      "totalViews": 40689,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Viejos Lesbianos VS Trasvestis Espaciales": {
      "id": "Viejos Lesbianos VS Trasvestis Espaciales",
      "name": "Viejos Lesbianos VS Trasvestis Espaciales",
      "kind": "other",
      "latestTimestamp": 1749528365000,
      "totalViews": 27181,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    },
    "Violet Evergarden": {
      "id": "Violet Evergarden",
      "name": "Violet Evergarden",
      "kind": "other",
      "latestTimestamp": 1699645280000,
      "totalViews": 18208,
      "viewsLast180d": 0,
      "viewsLast7d": 0,
      "monthlyGrowth": 0,
      "weeklyGrowth": 0
    }
  },
  "ranking_notes": {
    "populares_sofi_tv": "month_over_month_view_growth_with_fallback_to_current_views",
    "noche_de_peliculas": "month_over_month_movie_view_growth_with_fallback_to_current_views",
    "top_anime_semana": "week_over_week_view_growth_with_fallback_to_current_views"
  }
};
