window.REFERENCE_IMAGES = {
  "Marvel": "images/reference/avengers-age-of-ultron.jpg",
  "One Piece": "images/reference/one-piece.jpg",
  "The Seven Deadly Sins": "images/reference/the-seven-deadly-sins.png",
  "The Seven Deadly Sins: Movies & Specials": "images/reference/the-seven-deadly-sins-movies-specials.png",
  "Saint Seiya": "images/reference/saint-seiya.png",
  "The Legend of Korra": "images/reference/the-legend-of-korra.png",
  "NieR:Automata Ver1.1a": "images/reference/nier-automata-ver1-1a.jpg",
  "Brokeback Mountain": "images/reference/brokeback-mountain.jpg",
  "Bakemonogatari": "images/reference/bakemonogatari.png",
  "Vinland Saga": "images/reference/vinland-saga.jpg",
  "The Matrix": "images/reference/the-matrix.png",
  "Re:Zero − Starting Life in Another World": "images/reference/re-zero-starting-life-in-another-world.jpg",
  "Ergo Proxy": "images/reference/ergo-proxy.jpg",
  "Black Clover": "images/reference/black-clover.jpg",
  "My Hero Academia": "images/reference/my-hero-academia.png",
  "Sword Art Online": "images/reference/sword-art-online.jpg",
  "My Dress-Up Darling": "images/reference/my-dress-up-darling.jpg",
  "Fate/Zero": "images/reference/fate-zero.jpg",
  "Minecraft": "images/reference/minecraft.png",
  "Uma Musume: Pretty Derby: Movies & Specials": "images/reference/uma-musume-pretty-derby-movies-specials.jpg",
  "Sword Art Online: Movies & Specials": "images/reference/sword-art-online-movies-specials.jpg",
  "Dragon Ball Super: Movies & Specials": "images/reference/dragon-ball-super-movies-specials.png",
  "Saw": "images/reference/saw.jpg",
  "The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat": "images/reference/the-world-s-finest-assassin-gets-reincarnated-in-another-world-as-an-aristocrat.jpg",
  "Fate/strange Fake": "images/reference/fate-strange-fake.jpg",
  "Spider-Man": "images/reference/spider-man.png",
  "Avengers: Age of Ultron": "images/reference/avengers-age-of-ultron.jpg",
  "Kaiju No. 8": "images/reference/kaiju-no-8.jpg",
  "Monsters vs. Aliens": "images/reference/monsters-vs-aliens.jpg",
  "Naruto": "images/reference/naruto.jpg",
  "Steins;Gate": "images/reference/steins-gate.jpg",
  "Kill la Kill": "images/reference/kill-la-kill.jpg",
  "Mushoku Tensei: Movies & Specials": "images/reference/mushoku-tensei-movies-specials.png",
  "Fate/stay night": "images/reference/fate-stay-night.jpg",
  "The Shannara Chronicles": "images/reference/the-shannara-chronicles.jpg",
  "Naruto: Movies & Specials": "images/reference/naruto-movies-specials.jpg",
  "Hajime no Ippo: Movies & Specials": "images/reference/hajime-no-ippo-movies-specials.png",
  "Gintama: Movies & Specials": "images/reference/gintama-movies-specials.png",
  "Puella Magi Madoka Magica: Movies & Specials": "images/reference/puella-magi-madoka-magica-movies-specials.jpg",
  "Kaguya-sama: Love Is War: Movies & Specials": "images/reference/kaguya-sama-love-is-war-movies-specials.jpg",
  "Megamind": "images/reference/megamind.jpg"
};
