window.tailwind = window.tailwind || {};
window.tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#131313",
        "primary": "#ffb4aa",
        "inverse-surface": "#e5e2e1",
        "surface-container": "#201f1f",
        "on-surface-variant": "#e9bcb6",
        "primary-fixed": "#ffdad5",
        "outline": "#af8782",
        "on-surface": "#e5e2e1",
        "primary-container": "#e50914",
        "background": "#131313",
        "secondary-container": "#4a8eff",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed": "#001a41",
        "error": "#ffb4ab",
        "secondary": "#adc7ff",
        "on-primary-container": "#fff7f6",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "on-secondary": "#002e68",
        "surface-container-lowest": "#0e0e0e",
        "surface-bright": "#3a3939",
        "on-secondary-fixed-variant": "#004493",
        "tertiary-fixed": "#d5e3ff",
        "surface-tint": "#ffb4aa",
        "primary-fixed-dim": "#ffb4aa",
        "inverse-on-surface": "#313030",
        "on-tertiary-fixed": "#001b3c",
        "tertiary-container": "#0072d7",
        "surface-container-highest": "#353534",
        "tertiary": "#a7c8ff",
        "secondary-fixed": "#d8e2ff",
        "on-tertiary": "#003061",
        "tertiary-fixed-dim": "#a7c8ff",
        "surface-dim": "#131313",
        "outline-variant": "#5e3f3b",
        "inverse-primary": "#c0000c",
        "error-container": "#93000a",
        "on-tertiary-container": "#f8f9ff",
        "on-secondary-container": "#00285b",
        "secondary-fixed-dim": "#adc7ff",
        "surface-variant": "#353534",
        "on-background": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "on-primary-fixed-variant": "#930007",
        "on-primary-fixed": "#410001",
        "on-primary": "#690003",
        "on-tertiary-fixed-variant": "#004689"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
};
